"""'a'

Revision ID: ce91df3cab6e
Revises: 
Create Date: 2019-11-03 16:07:11.471055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce91df3cab6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaders',
    sa.Column('field1', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Team', sa.Text(), nullable=True),
    sa.Column('Gamesplayed', sa.Integer(), nullable=True),
    sa.Column('AverageMin', sa.Float(), nullable=True),
    sa.Column('FGM', sa.Float(), nullable=True),
    sa.Column('FGA', sa.Float(), nullable=True),
    sa.Column('FG%', sa.Float(), nullable=True),
    sa.Column('3PM', sa.Float(), nullable=True),
    sa.Column('3ATT', sa.Float(), nullable=True),
    sa.Column('3PT%', sa.Float(), nullable=True),
    sa.Column('FTM', sa.Float(), nullable=True),
    sa.Column('FTA', sa.Float(), nullable=True),
    sa.Column('FT%', sa.Float(), nullable=True),
    sa.Column('OREB', sa.Float(), nullable=True),
    sa.Column('DREB', sa.Float(), nullable=True),
    sa.Column('REB', sa.Float(), nullable=True),
    sa.Column('AST', sa.Float(), nullable=True),
    sa.Column('STL', sa.Float(), nullable=True),
    sa.Column('BLK', sa.Float(), nullable=True),
    sa.Column('TOV', sa.Float(), nullable=True),
    sa.Column('PPG', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('field1')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('pic', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('leaders')
    op.drop_table('daily')
    # ### end Alembic commands ###
